@baseUrl = http://localhost:3000/food/v1


GET {{baseUrl}}/food/type/HAMBURGUER
Content-Type: application/json

{
    "name": "X-NADA DUPLO",
    "price": 25.50,
    "type": "HAMBURGUER",
    "description": "3 kg de carne moída (escolha uma carne magra e macia)",
    "imageUrl": "https://www.typescriptlang.org/pt/docs/handbook/utility-types.html"
}



#

# GET {{baseUrl}}/food
#  Content-Type: application/json

# #

#  DELETE {{baseUrl}}/food/-OAeYg_5jQxsXSuKkrwI




